spring:
  profiles:
    active: dev
#    active: test
#server:
#  port: 9100
#  servlet:
#    context-path: /alibaba
##  port: 9101
##  port: 9102
#spring:
#  zipkin:
#    base-url: http://localhost:9411
##  profiles:
##    active: uat
#  application:
#    name: springcloudalibaba-module-orders
#  datasource:
#    password: jiaxu123
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://192.168.40.102:3306/orders?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    username: root
##  cloud:
##    zookeeper:
##      connect-string: 192.168.40.102:2181
#mybatis:
#  # 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
#  # 指定sql映射文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml
#debug: true
##eureka:
##  client:
##    register-with-eureka: true
##    fetch-registry: true
##    service-url:
##      defaultZone: http://springcloud-moudule-eureka-server-7001:7001/eureka,http://springcloud-moudule-eureka-server-7002:7002/eureka,http://springcloud-moudule-eureka-server-7000:7000/eureka
##  instance:
##    instance-id: ${spring.application.name}-${server.port}
##    prefer-ip-address: true
#
##springcloud-module-payment:
##  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
##feign超时时间设置
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
##feign日志打印
#logging:
#  level:
#
#    com.jiaxuch.orders.service.PaymentInterface: debug
